server:
  port: 9003
  shutdown: graceful

spring:
  application:
    name: order-service
  profiles:
    active: local


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      poolName: SpringBootJPAHikariCP
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 10000
      max-lifetime: 60000
      connection-timeout: 10000
      #validation-timeout: 30000
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
      #use-new-id-generator-mappings: true
    properties:
      hibernate.connection.provider_disables_autocommit: false
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
      jdbc:
        order_updates: true
        batch_versioned_data: false

  main:
    allow-bean-definition-overriding: true

  cloud:
    config:
      enabled: false

logging:
  level:
    root: info
